export const qk = {
  profile: ['profile'] as const,
  organization: ['organization'] as const,
  profiles: ['profiles'] as const,
  users: ['users'] as const,
  objects: (filters?: unknown) => ['objects', filters] as const,
  object: (id: string) => ['object', id] as const,
  objectMembers: (id: string) => ['object-members', id] as const,
  objectStages: (id: string, type?: string) => ['object-stages', id, type] as const,
  objectStage: (id: string) => ['object-stage', id] as const,
  objectEconomics: (id: string) => ['object-economics', id] as const,
  objectProgress: (id: string) => ['object-progress', id] as const,
  objectExpensesByCategory: (id: string) => ['object-expenses-cat', id] as const,
  objectExpensesByContour: (id: string) => ['object-expenses-contour', id] as const,
  activity: (id: string, filters?: unknown) => ['activity', id, filters] as const,
  stageTemplates: ['stage-templates'] as const,
  tools: (filters?: unknown) => ['tools', filters] as const,
  tool: (id: string) => ['tool', id] as const,
  toolMovements: (id: string) => ['tool-movements', id] as const,
  toolCategories: ['tool-categories'] as const,
  expenses: (filters?: unknown) => ['expenses', filters] as const,
  expenseCategories: ['expense-categories'] as const,
  contacts: ['contacts'] as const,
  attachments: (objectId: string, kind?: string, expenseScope?: string) =>
    ['attachments', objectId, kind, expenseScope] as const,
  signedUrl: (path: string) => ['signed-url', path] as const,
  requests: (filters?: unknown) => ['requests', filters] as const,
  dashboard: ['dashboard'] as const,
}
